from vnu.application.common.error import ApplicationError


class MusicProfileNotFoundError(ApplicationError): ...


class MusicProfileAlreadyExistsError(ApplicationError): ...


class MusicUploadNotFoundError(ApplicationError): ...


class ConnectionNotFoundError(ApplicationError): ...


class NotificationNotFoundError(ApplicationError): ...


class DuplicateMusicActionError(ApplicationError): ...


class InvalidMusicActionError(ApplicationError): ...


class ForbiddenMusicActionError(ApplicationError): ...
